image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      npm i
    command: |
      # Fix for gitpod snapshots losing the value of $GITPOD_REPO_ROOT more on https://github.com/gitpod-io/gitpod/issues/9804
      if [ "$GITPOD_REPO_ROOT" == '/workspace' ]; then
        export GITPOD_REPO_ROOT="$THEIA_WORKSPACE_ROOT"
      fi
      bash .gp/bash/startup.sh
